#
# Variables:
#
CC = gcc
BIN = CodeWar
SRC = \
	test2.c\
	CodeWar.c\
	affichage.c\
	debug.c\
	typage_operande.c\
	arguments.c\
	commandes.c\
	interpreteur.c\
	modifications.c\
	flags.c
OBJ = \
	test2.o\
 	CodeWar.o\
	affichage.o\
	debug.o\
	typage_operande.o\
	arguments.o\
	commandes.o\
	interpreteur.o\
	modifications.o\
	flags.o
 
#
# Flags d'erreurs:
#
ERROR_CFLAGS = -Wall -W -pedantic --export-dynamic
 	
 
#
# Flags pour le compilateur:
#
GLIB_CFLAGS = $$(pkg-config --cflags glib-2.0)
PANGO_CFLAGS = $$(pkg-config --cflags pango)
GTK_CFLAGS = $$(pkg-config --cflags gtk+-2.0)
GLADE_CFLAGS= $$(pkg-config --cflags --libs libglade-2.0)

CFLAGS = $(ERROR_FLAGS) $(GLIB_CFLAGS) $(PANGO_CFLAGS) $(GTK_CFLAGS) $(GLADE_CFLAGS)
 
 
#
# Flags pour l'editeur de liens:
#
GLADE_LDFLAGS= $$(pkg-config --cflags --libs libglade-2.0)
GLIB_LDFLAGS = $$(pkg-config --libs glib-2.0)
PANGO_LDFLAGS = $$(pkg-config --libs pango)
GTK_LDFLAGS = $$(pkg-config --libs gtk+-2.0)
 
LDFLAGS = $(ERROR_FLAGS) $(GLIB_LDFLAGS) $(PANGO_LDFLAGS) $(GTK_LDFLAGS) $(GLADE_LDFLAGS)
 
 
#
# Construction du programme:
#
all: $(BIN)
 
$(BIN): $(SRC)
	$(CC) $(CFLAGS) -c $(SRC)
	$(CC) $(LDFLAGS) -o $(BIN) $(OBJ)
 
 
#
# Nettoyage:
#
clean:
	rm -f *.o *~ core $(BIN)
 
